{% set name = "geosci" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 5b0d553ab761a79f240e1de007ebaffb3497d314cb61b45800316624df5e85ac

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - folium
    - ipyleaflet
    - pyshp
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - geosci

about:
  home: "https://github.com/coliaxu/geosci"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for interactive mapping"
  doc_url: https://coliaxu.github.io/geosci
  dev_url: https://github.com/coliaxu/geosci

extra:
  recipe-maintainers:
    - coliaxu
